### ISSUE TITLE
Would you consider maintaining official packages on Fedora?

### ISSUE THREAD

**Issue by pemensik** [ganto/copr-lxc4#17]
Hi,

I have checked your COPR repository and it seems quite good and maintained with great care. Some of your packages are not yet officially packaged on Fedora. Could you please consider adding missing packages to [Fedora Review](https://fedoraproject.org/PackageReviewStatus/) process? It seems to me they would pass fine and you are already [a packager](https://accounts.fedoraproject.org/user/ganto/).

I miss those packages you have already prepared:
- distrobuilder
- raft
- rubygem-ruby-lxc
- dqlite

Since you have already spent nontrivial effort to make and maintain them, could you maintain them in Fedora directly, please? Is there anything I can help you with making them official? I guess you could ask co-maintainer rights on the rest of packages also. Is there specific reason why you keep them updated here, but not in official repositories?

**Comment by ganto** [comment]
> distrobuilder were released in new version few days ago. I wanted to propose an update, but you have updated it yourself in the mean time.

Ya, I saw that they made a new release so I quickly bumped the version in the spec file.

> Could simpler packages be pushed to Fedora and lxd left to later time?

Ya, that's what I did with raft and dqlite but I still need an approval from Fedora legal because they use LGPLv3 with an exception clause. If I get LXD properly build on Fedora again one day, I might submit it maybe too... Let's see how it goes.

Regarding distrobuilder and umoci: Since you seem to use these tools regularly why don't you take over maintainership for those (I could be a co-maintainer if you wish)? 
* `umoci` should be nearly no work at all. They have a release maybe once a year. 
* `distrobuilder` might be a bit more effort depending on how much time you want to spend. When following their PRs and issues I feel it's still quite a laborious approach to keep this working for all different distributions. But it was no different with the old templates. Still I personally preferred the "old" way to create containers with the shell script templates that's why I also still [package those](https://copr-dist-git.fedorainfracloud.org/cgit/ganto/lxc4/lxc-templates-extra.git). But also not sure how well they still work nowadays. I just felt they were more approachable.

I don't use both of these tools myself (only tried them once when they were new to me a few years ago) and I'm not attached at all to those spec files. You can take my spec files and submit them so that they are good for something at least. :smiley:

**Comment by mrmateo** [comment]
I really appreciate the work you have been doing to keep this going @ganto -- I use it every day for my dev workflow. I don't have much to add to the conversation as I am not too familiar with the packaging process but LXD does release an LTS version (currently based on 4.0) that is supported through 2025 and is limited to only bugfixes and very minor improvements. I think your concern of there being breaking changes in LXD versions is a valid one so maybe having only the LTS version in Fedora might be easier to maintain (i.e. hopefully nothing breaking b/w versions)?
