### ISSUE TITLE
Updating to LXD 4.1/4.2

### ISSUE THREAD

**Issue by stemcc** [ganto/copr-lxc4#2]
I'm curious if the plan for this package is to track the LTS or feature releases of LXD. A lot of helpful bug fixes for LXD virtual machine support has been merged in 4.1 and continues in 4.2.

**Comment by ganto** [comment]
My original plan was to track latest feature releases for Fedora in this repository and then maybe have another LXD LTS repository for CentOS.

Sorry, but so far I haven't succeeded to build lxd-4.x with the new Fedora golang RPM macros. I'll try to find a bit of free time on one of the next weekends. Since Fedora 30 is EoL now, it might have become easier by now.

**Comment by ganto** [comment]
Actually I'm not a big fan of LXD on CentOS 7 or 8. The last time I tried, the virtual machine support didn't work because of some feature being disabled in the qemu build that were required by LXD. Also there is no way to disable VM support in LXD. At the moment I try to keep up with LXD on Fedora but also there I have multiple build issues that are hard to debug.

**Comment by derkuci** [comment]
Thanks for the heads up.  My main interest is with the containers so qemu/vm don't really bother me.  So far I haven't got problems (except that I had to setup subuid/subgid before enabling the services on CentOS 8).

Good luck with lxc4 on Fedora!  If you happen to have a build on centos, I can certainly help test; but definitely no worries if you don't plan to.  Thanks.

**Comment by ganto** [comment]
I definitely don't plan to put effort into packaging LXD for CentOS in the future. The LXD LTS release simply doesn't fit with the feature set that CentOS provides and I'd prefer to play around with the tons of LXD features instead of sticking with CentOS (and then figuring out that one after the other cannot work). I'm sorry, but I better communicate this clearly instead of raising false expectations.
