### ISSUE TITLE
request: LXC 5 series

### ISSUE THREAD

**Issue by lemonzest79** [ganto/copr-lxc4#20]
Hiya, thanks for your continued work on these packages, I just noticed LXD and LXCFS have been updating, is there any plans to upgrade the standalone LXC to its 5 version, its current version is 5.0.1 wheres fedora and your packages are still on 4.0.12 I think, many thanks to you and your packages :)

**Comment by ganto** [comment]
Actually I'm already working on it since a few weeks. There are various build and runtime issues such as lxc/lxc#4182 and lxc/lxc#4118 especially with io_uring support enabled as this was always the case with my package.

I just made a build with disabled io_uring support (6fb21091f4f711991a96cafc84ff12e424447f70) so at least you have something for testing but it seems that there are even more build issues (https://copr.fedorainfracloud.org/coprs/ganto/lxc4/build/4747230/).

Please let me know how the package works for you.

**Comment by ganto** [comment]
Since a few months lxc-5.0.x is available for all architectures now via my COPR repository. Please open a new issue if something doesn't work for you.
