### ISSUE TITLE
lxcfs fails to start on Silverblue with missing directory

### ISSUE THREAD

**Issue by bketelsen** [ganto/copr-lxc4#36]
/var/lib/lxcfs is not created before lxcfs tries to start.

I think the unit file needs an `ExecStartPre` similar to [this one](https://github.com/zabbly/incus/blob/9bfd0d7f28cf12532daf2f7685b263fa27e345d5/systemd/incus-lxcfs.service#L9)

**Comment by bketelsen** [comment]
[lxcfs-0001-mkdir.patch.txt](https://github.com/ganto/copr-lxc4/files/13745029/lxcfs-0001-mkdir.patch.txt)

**Comment by bketelsen** [comment]
I don't know rpm/spec wizardry, but this is the patch that should fix things.

**Comment by bketelsen** [comment]
actually that patch might be backwards... it should add the ExecStartPre, not remove it. I'm a rookie.

**Comment by ganto** [comment]
I think this should be reported to the Fedora [lxcfs](https://packages.fedoraproject.org/pkgs/lxcfs/lxcfs/) package. I'm only rebuilding the package with newer lxcfs releases before the Fedora maintainer also picks them up. However, I don't deviate from it so that's easy possible to update between the COPR and upstream packages.

**Comment by ganto** [comment]
This should be fixed now in `lxcfs-6.0.0-0.1` (c4a54a190cf88d69b97af6a9f80e87673d8f6155)
