### ISSUE TITLE
Ready for use?

### ISSUE THREAD

**Issue by jmhickman** [ganto/copr-lxc4#4]
I was a long time user of the lxc3 packages your provided. Thank you very much for your work in that area!

I found the lxc4 repo, but the page on copr very much makes it seem as though these packages aren't really ready for use yet. There aren't instructions included as there were in the lxc3 package page.

Are these packages ready for general use? If so, can documentation for their installation be provided? Even just a "Do the same things as you did for the lxc3" packages would be fine if the steps are indeed the same.

**Comment by ganto** [comment]
I'm now using these packages since a few months, migrated most of the stuff from [copr-lxc3](https://copr.fedorainfracloud.org/coprs/ganto/lxc3) to the lxc4 repository, so I would say, yes, it's ready for use.

I also created a Github [wiki](https://github.com/ganto/copr-lxc4/wiki) with some installation instructions and some initial documentation. And yes, the steps are the same ;-). If you miss something, please let me know.
